apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
  namespace: hello-gitops
data:
  index.html: |
    <html>
      <head>
        <title>GitOps Demo</title>
      </head>
      <body>
        <h1>Hello World RANIA HHHHa/h1>
        <h2>Deployed with Argo CD</h2>
      </body>
    </html>

